# Generated by Django 3.1.7 on 2021-04-15 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20210415_1152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0002_auto_20210415_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=38)),
                ('description', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('A', 'Asamblea'), ('C1', 'Charla'), ('C2', 'Conferencia'), ('C3', 'Convenio'), ('N', 'Novatada'), ('P', 'Proyecto'), ('R', 'Reunión')], max_length=2)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('id_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
                ('id_suborg_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.suborganization')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('C1', 'Carta'), ('C2', 'Constitución'), ('C3', 'Convenio'), ('E', 'Evidenia de reunión'), ('P', 'Propuesta de proyecto'), ('S', 'Solicitud')], max_length=2)),
                ('id_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('id_writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
