# Generated by Django 3.1.7 on 2021-04-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210415_1152'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='id_tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
        migrations.AddField(
            model_name='suborganization',
            name='id_member_in_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
