# Generated by Django 3.1.7 on 2021-04-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_sub_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.suborganization'),
        ),
        migrations.AddField(
            model_name='professor',
            name='id_faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_career',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.career'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.faculty'),
        ),
    ]
