# Generated by Django 3.1.7 on 2021-04-22 22:10

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210415_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ambassador',
            field=models.URLField(max_length=300, null=True, unique=True, validators=[user.validators.ambassador_valid_url]),
        ),
    ]
