# Generated by Django 3.1.7 on 2021-04-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_member_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='social_links',
            field=models.JSONField(null=True),
        ),
    ]
